# Generated by Django 4.2.19 on 2025-03-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0002_casesheet_postmartam_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesheet',
            name='postmartam_report',
        ),
    ]
