# Generated by Django 5.1.4 on 2025-03-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50, unique=True)),
                ('hospitaladdress', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=200)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('contact_no', models.CharField(max_length=15)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, upload_to='image')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Acciedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('accidentdetails', models.CharField(max_length=200)),
                ('media', models.ImageField(blank=True, upload_to='image')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentid', to='Personapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.CharField(max_length=50, unique=True)),
                ('addressline1', models.CharField(max_length=250)),
                ('addressline2', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Missingperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('missingpersonpic', models.ImageField(upload_to='image')),
                ('gender', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('missingdate', models.CharField(max_length=200)),
                ('missingplace', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('identificationmark', models.CharField(max_length=200)),
                ('bloodgroup', models.CharField(max_length=200)),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='Personapp.login')),
                ('stationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.hospital')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('contactno', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='UserComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=300)),
                ('subject', models.CharField(max_length=200)),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('replay', models.TextField(blank=True, max_length=500, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
    ]
