# Generated by Django 5.1.4 on 2025-01-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='usertype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
