# Generated by Django 5.1.4 on 2025-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesheet',
            name='postmartam_report',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
