# Generated by Django 5.1.4 on 2025-01-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0002_login_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50, unique=True)),
                ('hospitaladdress', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=200)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
    ]
