# Generated by Django 4.2.19 on 2025-03-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0003_remove_casesheet_postmartam_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesheet',
            name='postmortem_report',
            field=models.FileField(blank=True, null=True, upload_to='postmortem_reports/'),
        ),
    ]
