# Generated by Django 5.1.4 on 2025-01-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0003_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('contactno', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
    ]
