# Generated by Django 5.1.4 on 2025-02-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0004_alter_login_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='Missingperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('missingpersonpic', models.ImageField(upload_to='image')),
                ('gender', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('missingdate', models.CharField(max_length=200)),
                ('missingplace', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('identificationmark', models.CharField(max_length=200)),
                ('bloodgroup', models.CharField(max_length=200)),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('stationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationid', to='Personapp.login')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='Personapp.login')),
            ],
        ),
    ]
