# Generated by Django 5.1.4 on 2025-02-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0005_alter_login_usertype_missingperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='stationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.station'),
        ),
    ]
