# Generated by Django 5.1.4 on 2025-02-12 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0006_alter_missingperson_stationid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
    ]
