# Generated by Django 5.1.4 on 2025-02-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0008_usercomp_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomp',
            name='complaint',
            field=models.TextField(max_length=300),
        ),
    ]
