# Generated by Django 5.1.4 on 2025-02-12 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0009_alter_usercomp_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomp',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
