# Generated by Django 4.2.19 on 2025-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0014_rename_created_at_stationenquiry_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationenquiry',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
