# Generated by Django 5.1.4 on 2025-02-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0016_hospitalenquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalEnquiry',
        ),
    ]
