# Generated by Django 5.1.4 on 2025-03-01 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0017_delete_hospitalenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('contact_no', models.CharField(max_length=15)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login')),
            ],
        ),
    ]
