# Generated by Django 5.1.4 on 2025-03-01 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0019_alter_casesheet_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.login'),
        ),
    ]
