# Generated by Django 5.1.4 on 2025-03-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0020_alter_casesheet_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.hospital')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.station')),
            ],
        ),
    ]
