# Generated by Django 4.2.19 on 2025-03-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0021_hospitalenquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalEnquiry',
        ),
    ]
