# Generated by Django 4.2.19 on 2025-03-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0022_delete_hospitalenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesheet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='case_files/'),
        ),
        migrations.CreateModel(
            name='HospitalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.hospital')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personapp.station')),
            ],
        ),
    ]
