# Generated by Django 4.2.19 on 2025-03-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0023_casesheet_file_hospitalenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='file',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
